### ISSUE TITLE
'foldl' function not available

### ISSUE THREAD

**Issue by jkleiser** [nukata/lisp-in-dart#1]
In the Dart source code of this Lisp, lots of functions (+, *, ...) are implemented by using a foldl function (line 35), yet there is no foldl function, or similar as far as I can see, available for use in Lisp code.

**Comment by nukata** [comment]
Sorry, I missed your issue.
Try inserting the following code at line 316.

```Dart
    def("foldl", 3, (List a) {
      var f = a[2];
      return foldl(a[0], a[1], (x, y) => this.eval(
              new Cell(f,
                  new Cell(qqQuote(x),
                      new Cell(qqQuote(y), null))),
              null));
    });
```

Here `a[2]` is a binary function in Lisp, and so you cannot pass it to `foldl` directly.  You have to build a binary function in Dart which makes `this`, the Lisp interpreter, apply `a[2]` to the arguments `(x, y)`.

Now you can use `foldl` in Lisp as follows:
```
> (foldl 1 '(2 3 4) *)
24
> (foldl 'a '((b c) (d e f)) cons)
((a b c) d e f)
> 
```

**Comment by jkleiser** [comment]
Thanks a lot. I look forward to trying this.

On 1 Oct 2018, at 19:00, SUZUKI Hisao <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I missed your issue.
Try inserting the following code at line 316.

    def("foldl", 3, (List a) {
      var f = a[2];
      return foldl(a[0], a[1], (x, y) => this.eval(
              new Cell(f,
                  new Cell(qqQuote(x),
                      new Cell(qqQuote(y), null))),
              null));
    });

Here a[2] is a binary function in Lisp, and so you cannot pass it to foldl directly. You have to build a binary function in Dart which makes this, the Lisp interpreter, apply a[2] to the arguments (x, y).

Now you can use foldl in Lisp as follows:

> (foldl 1 '(2 3 4) *)
24
> (foldl 'a '((b c) (d e f)) cons)
((a b c) d e f)

**Comment by jkleiser** [comment]
Thanks. It works as you described. However, now I see that 'foldl' is not a standard function in Common Lisp or Emacs Lisp, and if I do `(foldl cons 'a '((b c) (d e f)))` in Racket (Scheme), then I get `'((d e f) (b c) . a)` as a result. Which kind of Lisp would behave as in your example?

**Comment by nukata** [comment]
Maybe no other Lisp would...
The code just behaves as my Dart function `foldl` in `lisp.dart` which behaves as `foldl(x0, xx, fn)` => `fn(fn(fn(x0, x1), x2), x3)` if `xx` is a Lisp list of `(x1 x2 x3)`.

If you want `(foldl cons 'a '((b c) (d e f)))` to result in `((d e f) (b c) . a)`, you can modify the code as follows:

```Dart
    def("foldl", 3, (List a) {
      var f = a[0];
      return foldl(a[1], a[2], (x, y) => this.eval(
              new Cell(f,
                  new Cell(qqQuote(y),
                      new Cell(qqQuote(x), null))),
              null));
    });
```

This results in `fn(x3, fn(x2, fn(x1, x0)))` for the above `x0` and `xx`.  It might look strange, but perhaps the designer of Racket might want the type of `x0` to be _the same_ as the type of result for `fn` = `cons`.

Note that, in Haskell, `foldl` has the type  `(a -> b -> a) -> a -> [b] -> a` and `foldl fn x0 xx` results in  `(fn (fn (fn x0 x1) x2) x3)` where the types of `x0` and the result must be _the same_.  Therefore, you cannot use `cons` ((`:`) in Haskell), which has the type `a -> [a] -> [a]`, as `fn` in Haskell.
