### ISSUE TITLE
Expand fn = eval(fn, env) here on Sym for speed

### ISSUE THREAD

**Issue by jkleiser** [nukata/lisp-in-dart#2]
On line 404 in lisp.dart I see the comment "Expand fn = eval(fn, env) here on Sym for speed."
As I understand it, that `fn = eval(fn, env)` is not being done. What is the reason for that, when the expansion (there) would have resulted in more speed?

**Comment by nukata** [comment]
> `fn = eval(fn, env)` is not being done.

It is done on line 410 in lisp.dart.
Note that if `fn is Sym`, the expression `eval(fn, env)` will return `globals[fn]`.
