### ISSUE TITLE
Possible to write a 'load' function?

### ISSUE THREAD

**Issue by jkleiser** [nukata/lisp-in-dart#3]
How easy would it be to extend this Lisp with a 'load' function that one could use at the REPL prompt to load/run a given Lisp script file?
As I see it, such a 'load' function would have to be synchronous, and if that's correct, one could not use the existing Reader class, since its read() method is async. Is that right?

**Comment by nukata** [comment]
Yes, it is right.
It is a challenging problem to implement the `load` function elegantly with `Stream` class of Dart.
