### ISSUE TITLE
setcar-rplaca, setcdr-rplacd confusion

### ISSUE THREAD

**Issue by jkleiser** [nukata/lisp-in-dart#4]
I took a closer look at how these four functions work, and I found it confusing that `setcar` is defined simply as a synonym for `rplaca`, and `setcdr` as a synonym for `rplacd`. This seems to be in conflict with what I read here https://www.gnu.org/software/emacs/manual/html_node/elisp/Modifying-Lists.html and here http://clhs.lisp.se/Body/f_rplaca.htm.

**Comment by nukata** [comment]
My Lisp behaves just like _Emacs Lisp_ for `rplaca` and `rplacd`.

In _Emacs Lisp_, `rplaca`is an alias for `setcar` and `rplacd` is an alias for `setcdr`.
Thus `(rplaca CELL NEWCAR)` sets the car of `CELL` to be `NEWCAR` and returns `NEWCAR`;
`(rplacd CELL NEWCDR)` sets the cdr of `CELL` to be `NEWCDR` and returns `NEWCDR`.

Regrettably, it is incompatible with _Common Lisp_ and legendary _Lisp 1.5_, in which those expressions return `CELL`.

**Comment by jkleiser** [comment]
Thanks!
